apiVersion: v1
kind: PersistentVolume
metadata:
  name: lychee-pv-photo-nfs
  labels:
    app: lychee
    tier: frontend
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem    
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
  - nolock
  - nfsvers=4.1
  nfs:
    server: 192.168.185.30
    path: "/vsan-fs/lychee"
    readOnly: false 


