apiVersion: v1
kind: PersistentVolume
metadata:
  name: lychee-pv-photo-nfs
  labels:
    app: lychee
    tier: frontend
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem    
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #mountOptions:
  #- nolock
  #- nfsvers=4.1
  nfs:
    server: 192.168.185.32
    path: "/lychee"
    readOnly: false 

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lychee-pvc-photo
  labels:
    app: lychee
    tier: frontend
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi

---


#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: lychee-pvc-photo
#  labels:
#    app: lychee
#    tier: frontend
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 5Gi
#  storageClassName: wcp-storage-general

---