apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: lychee
spec:
  topology:
    controlPlane:
      count: 1
      class: guaranteed-small
      storageClass: wcp-storage-general
    workers:
      count: 3
      class: guaranteed-medium
      storageClass: wcp-storage-general
  distribution:
    fullVersion: v1.15.5+vmware.1-tkg.1.85123d8
  settings:
    network:
      cni:
        name: calico
      services:
        cidrBlocks: ["198.51.100.0/12"]
      pods:
        cidrBlocks: ["192.0.2.0/16"]